/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.example.mymavlink.ackmsg;

import com.example.mymavlink.manger.MyLinkPacket;

import java.io.Serializable;

public abstract class BaseAckMsg implements Serializable {
    private static final long serialVersionUID = -7754622750478538539L;
    public int sysid;
    private int desId;
    private int srcId;
    public int compid;
    public int msgid;

    protected void decrypt(MyLinkPacket myLinkPacket) {
        this.srcId = myLinkPacket.srcId;
        this.desId = myLinkPacket.destId;
        this.compid = myLinkPacket.compid;
        this.msgid = myLinkPacket.msgid;
    }
}
