/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SysInfo PACKING
package com.MAVLink.Demo_heart;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * System information.
 */
public class msg_sysinfo extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_SysInfo = 150;
    public static final int MAVLINK_MSG_LENGTH = 3;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SysInfo;

    
    /**
     * Battery voltage
     */
    @Description("Battery voltage")
    @Units("")
    public int voltageBattery;
    
    /**
     * System state.
     */
    @Description("System state.")
    @Units("")
    public short sysState;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_SysInfo;

        packet.payload.putUnsignedShort(voltageBattery);
        packet.payload.putUnsignedByte(sysState);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a sysinfo message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.voltageBattery = payload.getUnsignedShort();
        this.sysState = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_sysinfo() {
        this.msgid = MAVLINK_MSG_ID_SysInfo;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_sysinfo( int voltageBattery, short sysState) {
        this.msgid = MAVLINK_MSG_ID_SysInfo;

        this.voltageBattery = voltageBattery;
        this.sysState = sysState;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_sysinfo( int voltageBattery, short sysState, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_SysInfo;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.voltageBattery = voltageBattery;
        this.sysState = sysState;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_sysinfo(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_SysInfo;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

        
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_SysInfo - sysid:"+sysid+" compid:"+compid+" voltageBattery:"+voltageBattery+" sysState:"+sysState+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_SysInfo";
    }
}
        