/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * System state.
 */
public class SYS_STATE {
   public static final int SYS_STOP = 0; /* System stop state | */
   public static final int SYS_RUN = 1; /* System run state | */
   public static final int SYS_STATE_ENUM_END = 2; /*  | */
}